### PR TITLE
Added soul on grid map + Enabled HMap on Android on Mobile

### PR DESCRIPTION
**Pull request by Ludofloria**
Hello !

I've managed to get the souls working on the grid view ;)
For now, the souls are moving according to a random pattern accross 4 cases around it's location (as it is on the flash version). But the icon is not rotating well ;)

Also, I've modified the detection of the flashvars content to make HMap work on Firefox for Android ;)

### CODE REVIEW

**Comment by Ryder-One** [comment]
Hi, 

Many thanks for your PR.

I'll start reviewing it now

**Comment by Ryder-One** [comment]
Do you think the PR will fix it : https://github.com/Ryder-One/hmap/issues/4 ?

**Review by Ryder-One — CHANGES_REQUESTED** [review]
This looks very good, but I want to try it first on the demo stage before merging into master. 

Do you think you'll be able to add a "soul" mode to http://ryderone.dynu.net/ ? Do you want me to put you in the right direction ?

**Comment by Ludofloria** [comment]
This one should fix #4 indeed ;)
To add a "soul" mode on your website, you just need the decoded data from the map ;)
I had some, but I lost it while pulling your latest changes :/
Maybe, next time I become Shaman I can drop the datas ;)
Eventually, to add souls on the map, you just have to set to true the "_s" var in the "_details" array

**Comment by Ludofloria** [comment]
UPDATE : Here is a full debug data, with souls on the map
https://pastebin.com/GLBpTSGN

**Comment by Ryder-One** [comment]
Hi, thank you for your quick answer.

By adding the "Soul" mode to the website, I meant : edit the index.html and create the checkbox to let users play with the shaman mode (that also mean generate random soul in the fake data)

**Comment by Ryder-One** [comment]
In the meantime, can you create a new PR with only the firefox bug correction ?

I'll be able to merge it right away.

**Comment by Ludofloria** [comment]
Oh okay.
Yes, I'll do it later this week then ;)

**Comment by Ludofloria** [comment]
Here. I've updated the branch to add Shaman Mode to the website ;)

**Review by Ryder-One — APPROVED** [review]

**Comment by Ryder-One** [comment]
Hi, 

Nice job ! I will look into it to see if we can improve the souls behavior. I think I will be able to make a new release this week-end with your contribution.

Thank you

**Comment by Ludofloria** [comment]
Yup, it might be improved (such as the icon rotation, it is absolutely not working)

**Comment by machandeze** [comment]
> This one should fix #4 indeed ;)

I am still experiencing #4 , but I found a quick workaround. I'm going to make a pull request.

**Pull request merged**
