### PR TITLE
Fix issue with DieVerdammten map

### LINKED ISSUE #7: Not Working on dieverdammten.de
The Map does not work on dieverdammten.de, while working on the other games (tested zombinoia and die2nite).

Was testing on Chrome 80 and Tampermonkey 4.9 on Chrome.
This is what the Browser Console tells me: 
http://prntscr.com/rj96m4

### PR DESCRIPTION
**Pull request by Ludofloria**
On DieVerdammten, non-visited zones are set to `null` or are `undefined`. To allow HMap to work on DV, those slight adjustment are necessary ;)
Fixes #7

### CODE REVIEW

**Comment by Ryder-One** [comment]
Honestly I don't have the time to try it. Did you try your modifications on other servers ? Is everything working well ?

**Comment by Ludofloria** [comment]
Hey there =)
I didn't test explorable ruins, but otherwise everything works well on Hordes, Die2Nite and DieVerdammten (I'm currently using it)

**Comment by Matoran** [comment]
Ruin is fully working on Hordes with the 3 additional pull requests I have done to your repo @Ludofloria . Tested more than 40 times now.

**Comment by Ryder-One** [comment]
I'm sorry but it looks like this PR has totally broken the ruin for me. At least the debug code I got in 2020 are not working now with the ruin mode. Since the game has not been updated, I'm not sure it will work now on hordes.fr

1. Are you testing on hordes.fr ?
2. Can you share debug code of your tests on the ruin with us ?

Thanks !

**Comment by Ludofloria** [comment]
I've tried it just now, and the ruins works fine.
Here's some debug :
https://pastebin.com/M3DCSDvi

**Comment by Ryder-One** [comment]
You tried on which server ? Hordes.fr ?

**Comment by Ludofloria** [comment]
Yup, I went into an Abandoned Hospital on Hordes.fr, in a distant town.

**Comment by Ludofloria** [comment]
I must mention that the Debug button gets hidden (you can click on its location, but it is not displayed)

**Pull request merged**
