### PR TITLE
fix ExploCommon for wrapped functions

### PR DESCRIPTION
**Pull request by Matoran**
I think this has been copy/paste from desert code and this case has not been modified

### CODE REVIEW

**Comment by Ryder-One** [comment]
Yes probably a copy paste mistake.

But I though that code was'nt working because it's executed for grease monkey only and this script is working with tampermonkey only.

Did you try it on grease monkey ? Is it working ?

**Comment by Matoran** [comment]
I have a fully working ruin right now, I can do the rest of the pull requests. Working on chrome/tampermonkey.

**Comment by Ryder-One** [comment]
Okay that is strange because the code you changed is dedicated to Greasemonkey. It's not supposed to run in the tampermonkey environment.

Anyway the correction looks good, I'm merging.

**Comment by Matoran** [comment]
I've fixed a lot of things, this one is probably useless for Tampermonkey^^. But that the first error I have fixed without actually doing a ruin.

**Pull request merged**
